### [Store] GET Hours
GET {{store_host}}/store/hours

### [Store] GET Products
GET {{store_host}}/store/products

### [Store] GET Warning
GET {{store_host}}/store/warn

### [Store] GET Error
GET {{store_host}}/store/error

### [Warehouse] Get Stock
GET {{warehouse_host}}/warehouse/stock